### ISSUE TITLE
Add option to set custom controllers directories

### ISSUE THREAD

**Issue by czj** [zombiezen/esbuild-plugin-stimulus#5]
Hello @zombiezen and first of all, many thanks for this plugin which is the missing piece to our esbuild + Stimulus "puzzle".

In our app we stimulus controller in many different directories,

- sidecar Stimulus controllers for ViewComponent components in `app/components/`
- generic components share by the 3 parts of our app in `app/javascript/controllers/shared`
- components for specific part of our app in directories like `app/javascript/controllers/shop` and `app/javascript/controllers/backoffice`

Due to this, some controllers cannot be imported (those outside `app/javascript/controllers`) and some others are namespaced `backoffice--` or `shop--` while they should not be.

Is there a way to pass a list of base directories to `esbuild`and/or your plugin to specify directories without adding code the the plugin ? Or should the plugin be modified ?

If anyone at @levups could be of any help, let us know :)

**Comment by zombiezen** [comment]
I might be misunderstanding your use case, but would something like this work? (untested)

```javascript
import { definitions as sidecarDefinitions } from 'stimulus:./app/components';
import { definitions as sharedDefinitions } from 'stimulus:./app/javascript/controllers/shared';
import { definitions as shopDefinitions } from 'stimulus:./app/javascript/controllers/shop';
import { definitions as backofficeDefinitions } from 'stimulus:./app/javascript/controllers/backoffice';

const app = Application.start();
app.load(sidecarDefinitions);
app.load(sharedDefinitions);
app.load(shopDefinitions);
app.load(backofficeDefinitions);
```

**Comment by czj** [comment]
Indeed that's the kind of code (and output) I would like to have.

It does not work as is though, as this other code where the paths are relative to the compiled files

```javascript
import { definitions as sidecarDefinitions } from 'stimulus:./../components';
import { definitions as sharedDefinitions } from 'stimulus:./controllers/shared';
import { definitions as shopDefinitions } from 'stimulus:./controllers/shop';
import { definitions as backofficeDefinitions } from 'stimulus:./controllers/backoffice';

const app = Application.start();
app.load(sidecarDefinitions);
app.load(sharedDefinitions);
app.load(shopDefinitions);
app.load(backofficeDefinitions);
```

I'm sorry, I have very little knowledge about esbuild and even after reading your plugin source code and esbuild's documentation, I'm not really understanding how options/path/import is handled.

**Comment by czj** [comment]
Indeed that's the kind of code (and output) I would like to have.

The given paths should be relative to the compiled files to work :

```javascript
import { definitions as sidecarDefinitions } from 'stimulus:./../components';
import { definitions as sharedDefinitions } from 'stimulus:./controllers/shared';
import { definitions as shopDefinitions } from 'stimulus:./controllers/shop';
import { definitions as backofficeDefinitions } from 'stimulus:./controllers/backoffice';

const app = Application.start();
app.load(sidecarDefinitions);
app.load(sharedDefinitions);
app.load(shopDefinitions);
app.load(backofficeDefinitions);
```

Thanks a lot for your help !

**Comment by czj** [comment]
For the record you can even use this very compact syntax:

```javascript
application.load(import("stimulus:./../components"));
application.load(import("stimulus:./controllers/shared"));
application.load(import("stimulus:./controllers/shop"));
application.load(import("stimulus:./controllers/backoffice"));
```
