### ISSUE TITLE
Handle nested controllers

### ISSUE THREAD

**Issue by Intrepidd** [zombiezen/esbuild-plugin-stimulus#6]
Welcome to the hype :)

This plug-in doesn't recursively look through controller folders. 

If you do several imports it works but the definitions are not prefixed with the namespace as expected 

How about adding resursive lookup of controllers?

**Comment by zombiezen** [comment]
> Welcome to the hype :)

Thanks! Did I get linked somewhere? 😅

> This plug-in doesn't recursively look through controller folders.
> 
> If you do several imports it works but the definitions are not prefixed with the namespace as expected
> 
> How about adding resursive lookup of controllers?

Hm, there is logic to recurse into subdirectories: https://github.com/zombiezen/esbuild-plugin-stimulus/blob/f8e57f9a680128ee94f85c59b54c9a04da202646/src/index.ts#L53-L60

Can you provide a [Minimal, Reproducible Example](https://stackoverflow.com/help/minimal-reproducible-example) of what you did and what isn't working for you?

**Comment by Intrepidd** [comment]
> Thanks! Did I get linked somewhere? 😅

Not directly but with rails 7 embracing esbuild this plugin is gonna get some attention I'm sure :) 

So realised the issue is that if there are 2 levels of recursion, the identifier ignores the first level of recursion.

Here is the repro : https://github.com/Intrepidd/esbuild-stimulus-issue

I have `controller/directory1/directory2/baz_controller.js`, but in the outfile, here is what I get : 

```js
  var definitions = [
    { identifier: "directory1--bar", controllerConstructor: bar_controller_default },
    { identifier: "directory2--baz", controllerConstructor: baz_controller_default },
    { identifier: "foo", controllerConstructor: foo_controller_default }
  ];
```
I have `directory2--baz` when I actually expect `directory1--directory2--baz`

I guess a naive fix would look like : 

```diff
            result.push(...await walk(
              path.join(dir, ent.name),
              - ent.name + '--',
              + (prefix ? prefix + '--' : '') + ent.name + '--',
              moduleDir + '/' + ent.name,
            ));
```

So that the prefix is not reset for each recursive call

Thanks !

**Comment by Intrepidd** [comment]
Also `_` is replaced by `-` which breaks the folder name, for instance : 

`foo_bar/some_controller.js` will be `foo-bar--some` whereas it will be `foo_bar--some` with the existing `@stimulus/webpack-helpers` package
